#!/usr/bin/env bash
set -euo pipefail

if [[ ! -f .env ]]; then
  echo "Missing .env. Copy .env.example and configure the named Snowflake connection." >&2
  exit 1
fi
set -a
source .env
set +a
: "${SNOWFLAKE_CONNECTION_NAME:?Set SNOWFLAKE_CONNECTION_NAME in .env}"

snow sql -c "$SNOWFLAKE_CONNECTION_NAME" -q \
  "USE ROLE WELLBEING_DEMO_ADMIN;
   DROP TABLE IF EXISTS SCHOOL_WELLBEING_DEMO.MARTS.MART_SCHOOL_WELLBEING_TREND;
   DROP TABLE IF EXISTS SCHOOL_WELLBEING_DEMO.CORE.FCT_WELLBEING_RESPONSE;
   DROP VIEW IF EXISTS SCHOOL_WELLBEING_DEMO.STAGING.INT_WELLBEING_ANSWERS;
   DROP VIEW IF EXISTS SCHOOL_WELLBEING_DEMO.STAGING.INT_WELLBEING_SUBMISSION_CURRENT;
   DROP VIEW IF EXISTS SCHOOL_WELLBEING_DEMO.STAGING.INT_WELLBEING_SUBMISSION_LATEST;
   DROP VIEW IF EXISTS SCHOOL_WELLBEING_DEMO.STAGING.STG_WELLBEING_SUBMISSION_CHANGES;
   TRUNCATE TABLE SCHOOL_WELLBEING_DEMO.RAW.MONGO_WELLBEING_SUBMISSIONS;
   REMOVE @SCHOOL_WELLBEING_DEMO.RAW.WELLBEING_INTERNAL_STAGE PATTERN='.*batch_m1_c17d965e5b1c.*';"
