#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repository_root}"

if [[ ! -f .env ]]; then
  echo "Missing .env. Copy .env.example and configure Snowflake." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1091
source .env
set +a

: "${SNOWFLAKE_CONNECTION_NAME:?Set SNOWFLAKE_CONNECTION_NAME in .env}"

npm test
pnpm --dir apps/dashboard build

# Rerunning the ordered production-hardening DDL is part of the idempotency
# evidence. No PAT or private key is generated by these scripts.
snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -f infra/snowflake/00_roles.sql
snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -f infra/snowflake/02_raw_objects.sql
snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -f infra/snowflake/03_grants.sql
snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -f infra/snowflake/06_service_identities.sql

./scripts/dbt-command.sh source freshness
./scripts/dbt-command.sh build

snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -f infra/snowflake/05_tenant_reader_views.sql
snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -f infra/snowflake/07_operations_view.sql

for tenant in NORTH SOUTH; do
  tenant_lower="$(printf '%s' "${tenant}" | tr '[:upper:]' '[:lower:]')"
  if [[ "${tenant}" == "NORTH" ]]; then
    other_tenant="SOUTH"
  else
    other_tenant="NORTH"
  fi
  snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -q \
    "USE ROLE WELLBEING_DEMO_TRUST_${tenant}_READER;
     USE SECONDARY ROLES NONE;
     USE WAREHOUSE WELLBEING_DEMO_APP_WH;
     ALTER SESSION SET QUERY_TAG = 'wellbeing_demo_acceptance';
     EXECUTE IMMEDIATE \$\$
     DECLARE visible_rows NUMBER;
             leaked_rows NUMBER;
             tenant_check_failed EXCEPTION (-20005, 'Tenant isolation acceptance failed');
     BEGIN
       SELECT COUNT(*), COUNT_IF(TRUST_ID != 'trust_${tenant_lower}')
         INTO :visible_rows, :leaked_rows
       FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_${tenant}_SCHOOL_INDICATOR_ANALYSIS;
       IF (visible_rows = 0 OR leaked_rows != 0) THEN
         RAISE tenant_check_failed;
       END IF;
       RETURN 'trust_${tenant_lower}: ' || visible_rows || ' aggregate rows and zero leaked rows';
     END;
     \$\$;"

  if snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -q \
    "USE ROLE WELLBEING_DEMO_TRUST_${tenant}_READER;
     USE SECONDARY ROLES NONE;
     USE WAREHOUSE WELLBEING_DEMO_APP_WH;
     ALTER SESSION SET QUERY_TAG = 'wellbeing_demo_acceptance_expected_failure';
     SELECT COUNT(*)
     FROM SCHOOL_WELLBEING_DEMO.RAW.MONGO_WELLBEING_SUBMISSIONS;" >/dev/null 2>&1; then
    echo "Reader negative test failed: WELLBEING_DEMO_TRUST_${tenant}_READER reached RAW." >&2
    exit 1
  fi

  if snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -q \
    "USE ROLE WELLBEING_DEMO_TRUST_${tenant}_READER;
     USE SECONDARY ROLES NONE;
     USE WAREHOUSE WELLBEING_DEMO_APP_WH;
     ALTER SESSION SET QUERY_TAG = 'wellbeing_demo_acceptance_expected_failure';
     SELECT COUNT(*)
     FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_${other_tenant}_SCHOOL_INDICATOR_ANALYSIS;" >/dev/null 2>&1; then
    echo "Cross-tenant test failed: ${tenant} reader reached ${other_tenant} view." >&2
    exit 1
  fi
done

snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -q \
  "USE ROLE WELLBEING_DEMO_OBSERVER;
   USE SECONDARY ROLES NONE;
   USE WAREHOUSE WELLBEING_DEMO_APP_WH;
   ALTER SESSION SET QUERY_TAG = 'wellbeing_demo_acceptance';
   EXECUTE IMMEDIATE \$\$
   DECLARE health_rows NUMBER;
           health_check_failed EXCEPTION (-20006, 'Operational health acceptance failed');
   BEGIN
     SELECT COUNT(*) INTO :health_rows
     FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_PIPELINE_HEALTH_SECURE;
     IF (health_rows != 1) THEN
       RAISE health_check_failed;
     END IF;
     RETURN 'Operational health surface passed: one summary row';
   END;
   \$\$;"

if snow sql -c "${SNOWFLAKE_CONNECTION_NAME}" -q \
  "USE ROLE WELLBEING_DEMO_OBSERVER;
   USE SECONDARY ROLES NONE;
   USE WAREHOUSE WELLBEING_DEMO_APP_WH;
   ALTER SESSION SET QUERY_TAG = 'wellbeing_demo_acceptance_expected_failure';
   SELECT COUNT(*)
   FROM SCHOOL_WELLBEING_DEMO.RAW.MONGO_WELLBEING_SUBMISSIONS;" >/dev/null 2>&1; then
  echo "Observer negative test failed: WELLBEING_DEMO_OBSERVER reached RAW." >&2
  exit 1
fi

echo "Milestone 5 acceptance passed."
