-- Milestone 0: isolated database, schemas, and virtual warehouses.
-- Prerequisite: infra/snowflake/00_roles.sql completed successfully.

USE ROLE WELLBEING_DEMO_ADMIN;

CREATE DATABASE IF NOT EXISTS SCHOOL_WELLBEING_DEMO
  COMMENT = 'Public school survey data and generated pipeline metadata for learning';

CREATE SCHEMA IF NOT EXISTS SCHOOL_WELLBEING_DEMO.RAW
  COMMENT = 'Append-only source envelopes and load metadata';

CREATE SCHEMA IF NOT EXISTS SCHOOL_WELLBEING_DEMO.STAGING
  COMMENT = 'Typed and normalized source changes';

CREATE SCHEMA IF NOT EXISTS SCHOOL_WELLBEING_DEMO.CORE
  COMMENT = 'Conformed facts and dimensions';

CREATE SCHEMA IF NOT EXISTS SCHOOL_WELLBEING_DEMO.MARTS
  COMMENT = 'Aggregate product models and secure views';

CREATE SCHEMA IF NOT EXISTS SCHOOL_WELLBEING_DEMO.GOVERNANCE
  COMMENT = 'Policies, tenant mappings, and audit helpers';

CREATE WAREHOUSE IF NOT EXISTS WELLBEING_DEMO_LOAD_WH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'School wellbeing demo ingestion only';

CREATE WAREHOUSE IF NOT EXISTS WELLBEING_DEMO_TRANSFORM_WH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'School wellbeing dbt transformations only';

CREATE WAREHOUSE IF NOT EXISTS WELLBEING_DEMO_APP_WH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'School wellbeing dashboard queries only';

-- IF NOT EXISTS preserves existing objects. These ALTER statements also
-- correct cost-sensitive settings if an existing warehouse has drifted.
ALTER WAREHOUSE WELLBEING_DEMO_LOAD_WH SET
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

ALTER WAREHOUSE WELLBEING_DEMO_TRANSFORM_WH SET
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

ALTER WAREHOUSE WELLBEING_DEMO_APP_WH SET
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Verification output.
SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_WAREHOUSE();
SHOW DATABASES LIKE 'SCHOOL_WELLBEING_DEMO';
SHOW SCHEMAS IN DATABASE SCHOOL_WELLBEING_DEMO;
SHOW WAREHOUSES LIKE 'WELLBEING_DEMO_%';
