-- Milestone 0: minimum runtime privileges.
-- Prerequisites:
--   1. infra/snowflake/00_roles.sql
--   2. infra/snowflake/01_foundation.sql
--   3. infra/snowflake/02_raw_objects.sql

USE ROLE WELLBEING_DEMO_ADMIN;

-- ---------------------------------------------------------------------------
-- Loader: use only the load warehouse and RAW ingestion objects.
-- ---------------------------------------------------------------------------

GRANT USAGE ON WAREHOUSE WELLBEING_DEMO_LOAD_WH
  TO ROLE WELLBEING_DEMO_LOADER;

GRANT USAGE ON DATABASE SCHOOL_WELLBEING_DEMO
  TO ROLE WELLBEING_DEMO_LOADER;

GRANT USAGE ON SCHEMA SCHOOL_WELLBEING_DEMO.RAW
  TO ROLE WELLBEING_DEMO_LOADER;

-- Grant READ before WRITE because WRITE on an internal stage depends on READ.
GRANT READ ON STAGE
  SCHOOL_WELLBEING_DEMO.RAW.WELLBEING_INTERNAL_STAGE
  TO ROLE WELLBEING_DEMO_LOADER;

GRANT WRITE ON STAGE
  SCHOOL_WELLBEING_DEMO.RAW.WELLBEING_INTERNAL_STAGE
  TO ROLE WELLBEING_DEMO_LOADER;

GRANT INSERT, SELECT ON TABLE
  SCHOOL_WELLBEING_DEMO.RAW.MONGO_WELLBEING_SUBMISSIONS
  TO ROLE WELLBEING_DEMO_LOADER;

-- Deliberately absent: UPDATE, DELETE, TRUNCATE, CREATE TABLE, and access to
-- curated schemas. Raw history remains append-only for this role.

-- ---------------------------------------------------------------------------
-- Transformer: read RAW and build dbt-owned models downstream.
-- ---------------------------------------------------------------------------

GRANT USAGE ON WAREHOUSE WELLBEING_DEMO_TRANSFORM_WH
  TO ROLE WELLBEING_DEMO_TRANSFORMER;

GRANT USAGE ON DATABASE SCHOOL_WELLBEING_DEMO
  TO ROLE WELLBEING_DEMO_TRANSFORMER;

GRANT USAGE ON SCHEMA SCHOOL_WELLBEING_DEMO.RAW
  TO ROLE WELLBEING_DEMO_TRANSFORMER;

GRANT SELECT ON TABLE
  SCHOOL_WELLBEING_DEMO.RAW.MONGO_WELLBEING_SUBMISSIONS
  TO ROLE WELLBEING_DEMO_TRANSFORMER;

GRANT USAGE ON SCHEMA SCHOOL_WELLBEING_DEMO.STAGING
  TO ROLE WELLBEING_DEMO_TRANSFORMER;
GRANT USAGE ON SCHEMA SCHOOL_WELLBEING_DEMO.CORE
  TO ROLE WELLBEING_DEMO_TRANSFORMER;
GRANT USAGE ON SCHEMA SCHOOL_WELLBEING_DEMO.MARTS
  TO ROLE WELLBEING_DEMO_TRANSFORMER;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA
  SCHOOL_WELLBEING_DEMO.STAGING
  TO ROLE WELLBEING_DEMO_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA
  SCHOOL_WELLBEING_DEMO.CORE
  TO ROLE WELLBEING_DEMO_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA
  SCHOOL_WELLBEING_DEMO.MARTS
  TO ROLE WELLBEING_DEMO_TRANSFORMER;

-- Deliberately absent: WRITE access to the stage and DML privileges on RAW.

-- ---------------------------------------------------------------------------
-- Readers: use only the application warehouse and MARTS views.
-- ---------------------------------------------------------------------------

GRANT USAGE ON WAREHOUSE WELLBEING_DEMO_APP_WH
  TO ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
GRANT USAGE ON WAREHOUSE WELLBEING_DEMO_APP_WH
  TO ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;

GRANT USAGE ON DATABASE SCHOOL_WELLBEING_DEMO
  TO ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
GRANT USAGE ON DATABASE SCHOOL_WELLBEING_DEMO
  TO ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;

GRANT USAGE ON SCHEMA SCHOOL_WELLBEING_DEMO.MARTS
  TO ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
GRANT USAGE ON SCHEMA SCHOOL_WELLBEING_DEMO.MARTS
  TO ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;

-- Reader SELECT grants are deliberately object-specific. Granting ALL or
-- FUTURE views here would give each tenant role access to the other tenant's
-- secure view. Run 05_tenant_reader_views.sql after the dbt mart is built.

-- Deliberately absent: SELECT on MARTS tables and any access to RAW, STAGING,
-- CORE, GOVERNANCE, the load warehouse, or the transform warehouse.

-- ---------------------------------------------------------------------------
-- Verification output.
-- ---------------------------------------------------------------------------

SHOW GRANTS TO ROLE WELLBEING_DEMO_LOADER;
SHOW GRANTS TO ROLE WELLBEING_DEMO_TRANSFORMER;
SHOW GRANTS TO ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
SHOW GRANTS TO ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;
