-- Tenant-isolated reader views for Power BI and other dashboard clients.
-- Prerequisites:
--   1. infra/snowflake/00_roles.sql through 03_grants.sql
--   2. dbt has built MARTS.MART_SCHOOL_WELLBEING_TREND

USE ROLE WELLBEING_DEMO_ADMIN;

-- Remove the legacy blanket grants before creating either tenant view. If
-- retained, both reader roles would automatically receive every new view.
REVOKE SELECT ON FUTURE VIEWS IN SCHEMA SCHOOL_WELLBEING_DEMO.MARTS
  FROM ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
REVOKE SELECT ON FUTURE VIEWS IN SCHEMA SCHOOL_WELLBEING_DEMO.MARTS
  FROM ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;

REVOKE SELECT ON ALL VIEWS IN SCHEMA SCHOOL_WELLBEING_DEMO.MARTS
  FROM ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
REVOKE SELECT ON ALL VIEWS IN SCHEMA SCHOOL_WELLBEING_DEMO.MARTS
  FROM ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;

CREATE OR REPLACE SECURE VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_NORTH_SCHOOL_WELLBEING_TREND
  COMMENT = 'North-trust-only Power BI semantic view over the wellbeing trend mart'
AS
SELECT
    trust_id,
    school_id,
    school_classification,
    survey_period,
    question_code,
    eligible_submission_count,
    answered_response_count,
    missing_response_count,
    adverse_response_count,
    adverse_response_rate
FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_SCHOOL_WELLBEING_TREND
WHERE trust_id = 'trust_north';

CREATE OR REPLACE SECURE VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_SOUTH_SCHOOL_WELLBEING_TREND
  COMMENT = 'South-trust-only Power BI semantic view over the wellbeing trend mart'
AS
SELECT
    trust_id,
    school_id,
    school_classification,
    survey_period,
    question_code,
    eligible_submission_count,
    answered_response_count,
    missing_response_count,
    adverse_response_count,
    adverse_response_rate
FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_SCHOOL_WELLBEING_TREND
WHERE trust_id = 'trust_south';

CREATE OR REPLACE SECURE VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_NORTH_QUESTION_RESPONSE_DISTRIBUTION
  COMMENT = 'North-trust-only aggregate question response distribution'
AS
SELECT *
FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_QUESTION_RESPONSE_DISTRIBUTION
WHERE trust_id = 'trust_north';

CREATE OR REPLACE SECURE VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_SOUTH_QUESTION_RESPONSE_DISTRIBUTION
  COMMENT = 'South-trust-only aggregate question response distribution'
AS
SELECT *
FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_QUESTION_RESPONSE_DISTRIBUTION
WHERE trust_id = 'trust_south';

CREATE OR REPLACE SECURE VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_NORTH_SUPPORT_SIGNAL_SUMMARY
  COMMENT = 'North-trust-only aggregate non-diagnostic support signals'
AS
SELECT *
FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_SUPPORT_SIGNAL_SUMMARY
WHERE trust_id = 'trust_north';

CREATE OR REPLACE SECURE VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_SOUTH_SUPPORT_SIGNAL_SUMMARY
  COMMENT = 'South-trust-only aggregate non-diagnostic support signals'
AS
SELECT *
FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_SUPPORT_SIGNAL_SUMMARY
WHERE trust_id = 'trust_south';

CREATE OR REPLACE SECURE VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_NORTH_DATA_FRESHNESS
  COMMENT = 'North-trust-only aggregate pipeline freshness'
AS
SELECT *
FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_DATA_FRESHNESS
WHERE trust_id = 'trust_north';

CREATE OR REPLACE SECURE VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_SOUTH_DATA_FRESHNESS
  COMMENT = 'South-trust-only aggregate pipeline freshness'
AS
SELECT *
FROM SCHOOL_WELLBEING_DEMO.MARTS.MART_DATA_FRESHNESS
WHERE trust_id = 'trust_south';

GRANT SELECT ON VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_NORTH_SCHOOL_WELLBEING_TREND
  TO ROLE WELLBEING_DEMO_TRUST_NORTH_READER;

GRANT SELECT ON VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_SOUTH_SCHOOL_WELLBEING_TREND
  TO ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;

GRANT SELECT ON VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_NORTH_QUESTION_RESPONSE_DISTRIBUTION
  TO ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
GRANT SELECT ON VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_SOUTH_QUESTION_RESPONSE_DISTRIBUTION
  TO ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;

GRANT SELECT ON VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_NORTH_SUPPORT_SIGNAL_SUMMARY
  TO ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
GRANT SELECT ON VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_SOUTH_SUPPORT_SIGNAL_SUMMARY
  TO ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;

GRANT SELECT ON VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_NORTH_DATA_FRESHNESS
  TO ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
GRANT SELECT ON VIEW
  SCHOOL_WELLBEING_DEMO.MARTS.MART_TRUST_SOUTH_DATA_FRESHNESS
  TO ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;

SHOW FUTURE GRANTS IN SCHEMA SCHOOL_WELLBEING_DEMO.MARTS;
SHOW GRANTS TO ROLE WELLBEING_DEMO_TRUST_NORTH_READER;
SHOW GRANTS TO ROLE WELLBEING_DEMO_TRUST_SOUTH_READER;
