-- Milestone 5: workload-isolated service identities.
-- This script creates credential-less SERVICE users and grants exactly one
-- runtime role to each. Attach a network policy and generate role-restricted
-- PATs or configure workload identity/key-pair authentication separately.

USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS WELLBEING_DEMO_LOADER_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = 'WELLBEING_DEMO_LOADER'
  DEFAULT_WAREHOUSE = 'WELLBEING_DEMO_LOAD_WH'
  DEFAULT_NAMESPACE = 'SCHOOL_WELLBEING_DEMO.RAW'
  COMMENT = 'Production-shaped identity for wellbeing batch ingestion';

CREATE USER IF NOT EXISTS WELLBEING_DEMO_TRANSFORMER_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = 'WELLBEING_DEMO_TRANSFORMER'
  DEFAULT_WAREHOUSE = 'WELLBEING_DEMO_TRANSFORM_WH'
  DEFAULT_NAMESPACE = 'SCHOOL_WELLBEING_DEMO.STAGING'
  COMMENT = 'Production-shaped identity for wellbeing dbt builds';

CREATE USER IF NOT EXISTS WELLBEING_DEMO_DASHBOARD_NORTH_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = 'WELLBEING_DEMO_TRUST_NORTH_READER'
  DEFAULT_WAREHOUSE = 'WELLBEING_DEMO_APP_WH'
  DEFAULT_NAMESPACE = 'SCHOOL_WELLBEING_DEMO.MARTS'
  COMMENT = 'North deployment dashboard identity';

CREATE USER IF NOT EXISTS WELLBEING_DEMO_DASHBOARD_SOUTH_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = 'WELLBEING_DEMO_TRUST_SOUTH_READER'
  DEFAULT_WAREHOUSE = 'WELLBEING_DEMO_APP_WH'
  DEFAULT_NAMESPACE = 'SCHOOL_WELLBEING_DEMO.MARTS'
  COMMENT = 'South deployment dashboard identity';

CREATE USER IF NOT EXISTS WELLBEING_DEMO_OBSERVER_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = 'WELLBEING_DEMO_OBSERVER'
  DEFAULT_WAREHOUSE = 'WELLBEING_DEMO_APP_WH'
  DEFAULT_NAMESPACE = 'SCHOOL_WELLBEING_DEMO.MARTS'
  COMMENT = 'Operational health identity';

USE ROLE SECURITYADMIN;

GRANT ROLE WELLBEING_DEMO_LOADER
  TO USER WELLBEING_DEMO_LOADER_SVC;
GRANT ROLE WELLBEING_DEMO_TRANSFORMER
  TO USER WELLBEING_DEMO_TRANSFORMER_SVC;
GRANT ROLE WELLBEING_DEMO_TRUST_NORTH_READER
  TO USER WELLBEING_DEMO_DASHBOARD_NORTH_SVC;
GRANT ROLE WELLBEING_DEMO_TRUST_SOUTH_READER
  TO USER WELLBEING_DEMO_DASHBOARD_SOUTH_SVC;
GRANT ROLE WELLBEING_DEMO_OBSERVER
  TO USER WELLBEING_DEMO_OBSERVER_SVC;

SHOW USERS LIKE 'WELLBEING_DEMO_%_SVC';
