-- Milestone 6 phase 2: external stage and auto-ingest pipe.
-- Run only after AWS trusts the principal returned by DESC INTEGRATION.
-- Required Snowflake CLI template variable: -D "s3_bucket=<bucket-name>"

USE ROLE WELLBEING_DEMO_ADMIN;
USE DATABASE SCHOOL_WELLBEING_DEMO;
USE SCHEMA RAW;

CREATE STAGE IF NOT EXISTS WELLBEING_S3_STAGE
  URL = 's3://<% s3_bucket %>/region=uk/collection=wellbeing_submissions/'
  STORAGE_INTEGRATION = WELLBEING_DEMO_S3_INTEGRATION
  FILE_FORMAT = WELLBEING_NDJSON_FORMAT
  COMMENT = 'Versioned encrypted S3 landing for Snowpipe';

ALTER STAGE WELLBEING_S3_STAGE SET
  URL = 's3://<% s3_bucket %>/region=uk/collection=wellbeing_submissions/'
  STORAGE_INTEGRATION = WELLBEING_DEMO_S3_INTEGRATION
  FILE_FORMAT = WELLBEING_NDJSON_FORMAT;

CREATE PIPE IF NOT EXISTS WELLBEING_SUBMISSIONS_PIPE
  AUTO_INGEST = TRUE
  COMMENT = 'S3 event notifications through Snowflake-managed SQS into append-only raw history'
  AS
  COPY INTO SCHOOL_WELLBEING_DEMO.RAW.MONGO_WELLBEING_SUBMISSIONS
    (ENVELOPE, SOURCE_FILE, SOURCE_FILE_ROW_NUMBER, LOADED_AT, LOAD_RUN_ID)
  FROM (
    SELECT
      $1,
      METADATA$FILENAME,
      METADATA$FILE_ROW_NUMBER,
      METADATA$START_SCAN_TIME,
      CONCAT('snowpipe:', METADATA$FILENAME)
    FROM @SCHOOL_WELLBEING_DEMO.RAW.WELLBEING_S3_STAGE
  )
  PATTERN = '.*[.]ndjson[.]gz'
  FILE_FORMAT = (FORMAT_NAME = SCHOOL_WELLBEING_DEMO.RAW.WELLBEING_NDJSON_FORMAT)
  ON_ERROR = SKIP_FILE;

GRANT USAGE ON STAGE WELLBEING_S3_STAGE
  TO ROLE WELLBEING_DEMO_LOADER;
GRANT MONITOR ON PIPE WELLBEING_SUBMISSIONS_PIPE
  TO ROLE WELLBEING_DEMO_LOADER;

SHOW PIPES LIKE 'WELLBEING_SUBMISSIONS_PIPE' IN SCHEMA RAW;
SELECT SYSTEM$PIPE_STATUS('SCHOOL_WELLBEING_DEMO.RAW.WELLBEING_SUBMISSIONS_PIPE');
