-- Milestone 6 read-only operational evidence. Run after uploading fixtures.
USE ROLE WELLBEING_DEMO_LOADER;
USE WAREHOUSE WELLBEING_DEMO_LOAD_WH;
USE DATABASE SCHOOL_WELLBEING_DEMO;
USE SCHEMA RAW;

SELECT SYSTEM$PIPE_STATUS('WELLBEING_SUBMISSIONS_PIPE') AS PIPE_STATUS;

SELECT
  FILE_NAME,
  STATUS,
  ROW_COUNT,
  ERROR_COUNT,
  FIRST_ERROR_MESSAGE,
  PIPE_RECEIVED_TIME,
  LAST_LOAD_TIME
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'MONGO_WELLBEING_SUBMISSIONS',
  START_TIME => DATEADD('day', -14, CURRENT_TIMESTAMP()),
  PIPE_NAME => 'WELLBEING_SUBMISSIONS_PIPE'
))
WHERE FILE_NAME LIKE '%batch_m6_%'
ORDER BY LAST_LOAD_TIME DESC;

SELECT
  ENVELOPE:batch_id::STRING AS BATCH_ID,
  COUNT(*) AS RAW_ROW_COUNT,
  COUNT_IF(ENVELOPE:producer_metadata.contract_revision::STRING = '1.1') AS SCHEMA_DRIFT_ROW_COUNT
FROM MONGO_WELLBEING_SUBMISSIONS
WHERE ENVELOPE:batch_id::STRING LIKE 'batch_m6_live_%'
GROUP BY BATCH_ID;
